-- CreateTable
CREATE TABLE `maxs` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `max_temp` INTEGER NOT NULL DEFAULT 30,
    `max_humd` INTEGER NOT NULL DEFAULT 70,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
